name: Run tests
on:
  push:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Prettier
        run: npm install -g prettier@3.1.0

      # Check that we actually need to fix something
      - name: Run 'prettier --check'
        id: prettier_status
        run: |
          if prettier --check ${GITHUB_WORKSPACE}; then
            echo "result=pass" >> $GITHUB_OUTPUT
          else
            echo "result=fail" >> $GITHUB_OUTPUT
          fi

      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run 'prettier --write'
        if: steps.prettier_status.outputs.result == 'fail'
        run: prettier --write ${GITHUB_WORKSPACE}

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
